-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ --
-- MONITORS (<- monitors.conf + Monitor_Profiles/default.conf + LaptopDisplay.conf)
-- HOW TO:
--   · Find names/modes: `hyprctl monitors all` (use `desc:…` for portable
--     matching instead of HDMI-A-1/DP-2 when possible).
--   · mode = "preferred" | "highrr" | "highres" | "1920x1080@144" …
--   · position = "auto" (right of the rest) | "auto-left/up/down" | "0x0" | "1920x0" …
--   · scale = number or "auto". transform = 0-7 (rotation/flip).
-- NOTE: nwg-displays used to overwrite monitors.conf; THIS file is now the
-- source of truth — copy any nwg-displays output here by hand.
-- NOTE: the three generic fallback rules below overlap (same empty output);
-- kept in original order (last match wins), exactly as in monitors.conf.

-- Fallbacks for any unspecified output
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
hl.monitor({ output = "", mode = "highrr", position = "auto", scale = 1 })
hl.monitor({ output = "", mode = "highres", position = "auto", scale = 1 })

-- Explicit desktop layout matched by DESCRIPTION (stable across GPUs/ports —
-- connector names like DP-2/HDMI-A-1 can shift; `hyprctl monitors all` shows
-- current ones). Left: Fujitsu @60Hz · Right: HP OMEN @144Hz.
hl.monitor({ output = "desc:Fujitsu Siemens Computers GmbH P24W-6 LED YV5L004610", mode = "1920x1080@60", position = "0x0", scale = 1 })
hl.monitor({ output = "desc:HP Inc. OMEN by HP 25 3CQ1290501", mode = "1920x1080@144", position = "1920x0", scale = 1 })

-- Laptop display (was LaptopDisplay.conf, dynamically generated by lid binds;
-- all commented out — enable when on laptop-only setup):
-- hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1 })

-- Examples (from old monitors.conf comments):
-- hl.monitor({ output = "eDP-1", mode = "2560x1440@165", position = "0x0", scale = 1 })
-- hl.monitor({ output = "DP-1", mode = "preferred", position = "auto", scale = 1 })
-- hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "1920x0", scale = 1 }) -- offset example
-- To disable: hl.monitor({ output = "NAME", disabled = true })
-- To mirror:  hl.monitor({ output = "DP-3", mode = "1920x1080@60", position = "0x0", scale = 1, mirror = "DP-2" })
-- 10-bit: add bitdepth = 10 (breaks some screen capture; border colors stay 8-bit)
