#!/bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
##################### By: Rxyhn  ####################

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

## Environments
export PATH="${PATH}:${HOME}/.config/bspwm/bin"


# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Run power manager.
xfce4-power-manager &

# Run mpd if doesn't started.
[ -n "$(pidof mpd)" ] || mpd &

# Start X wallpaper.
feh --no-fehbg --bg-fill $HOME/.config/wallpapers/archkali.png

# Fix cursor.
xsetroot -cursor_name left_ptr 

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

if [[ $(xrandr -q | grep 'HDMI-1-1 connected') ]]; then
	xrandr --output HDMI-1-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --left-of HDMI-1-1
	bspc monitor HDMI-1-1 -d 1 2 3 4 5 6
	bspc monitor eDP-1 -d 7 8 9
else
	bspc monitor -d 1 2 3 4 5 6  
fi

rule -a kitty                       follow=on focus=on
rule -a Code                        follow=on focus=on
rule -a firefox                     follow=on focus=on
rule mpv                            state=floating
rule feh                            state=floating

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config border_width 4
config window_gap 10
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

#Idioma de teclado
setxkbmap es &
#Lanza a polybar
polybar cyn-bar &
#Conecta wifi eduroam
nmcli device wifi connect eduroam


bspc config normal_border_color "$BACKGROUND"
bspc config focused_border_color "$BACKGROUND"
config presel_feedback_color "$BACKGROUND"
pkill borders ; borders &
