# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000103)
$foreground = rgb(F8F9FB)
$color0 = rgb(000103)
$color1 = rgb(565345)
$color2 = rgb(8F494F)
$color3 = rgb(787070)
$color4 = rgb(837657)
$color5 = rgb(B09868)
$color6 = rgb(B1B3B7)
$color7 = rgb(EDEFF1)
$color8 = rgb(A6A7A9)
$color9 = rgb(736F5C)
$color10 = rgb(BF616A)
$color11 = rgb(A09595)
$color12 = rgb(AF9D74)
$color13 = rgb(EBCB8B)
$color14 = rgb(ECEFF4)
$color15 = rgb(EDEFF1)
